### PR TITLE
Resolves hps-dst _Issue35

### PR DESCRIPTION
**Pull request by omar-moreno**

### CODE REVIEW

**Comment by mholtrop** [comment]
I haven't had a chance to fully test this modification, but it seems to me that the storage model for SvtTrack changes due to the new code. This will have issues with "old" and "new" DST data. The "old" data, which is now on tape, will not be readable with the new implementation of this class.

At a **minimum** we would need to change: ClassDef(SvtTrack, 1);  to ClassDef(SvtTrack, 2); I.e. tell ROOT that this is a new version of the SvtTrack class.

A significant improvement on that minimum would be to take the automatically generated streamer and add it to the class by hand, then modify it to detect which version (1 or 2) of the SvtTrack the data is in and load the data properly depending on that switch. 
This is not so hard to do. If you want me to take care of that, I can.

**Comment by omar-moreno** [comment]
There is a test case in the "test" directory. Feel free to run it.

The old data should be read using the corresponding release. These changes
will only apply to future passes of the data.  I agree that the class
version needs to increase. I'll go ahead and do that.

As for modifying the streamer, that's something that we can look into doing
but it should be a separate issue. Please go ahead and open a new issue.

**Comment by omar-moreno** [comment]
The class version has been increased to 2.

**Comment by mholtrop** [comment]
Hi Omar,

I will try to test these mods soon. 

I guess it is a matter of coding philosophy whether you try to make the changes to the code backward compatible or not. I would say yes, if at all possible, make things backward compatible. Telling people that analyze data that they need version X of the HpsEvent lib for data processed on date Y is a recipe for confusion. In this case, I would say there is a way to keep the HpsEvent library backwards compatible, so we should do it, and I don’t see it as a separate issue, since it is dependent on the changes in Issue35. However, if there is a time pressure to get this issue resolved, put a deadline on the streamer mod, and if it is not done before the deadline, merge to master.

BTW, you seem to have assigned this to me. Did you assign the merge only or the completion of the this issue?

Best,
	Maurik

**Comment by omar-moreno** [comment]
I disagree.  Changing the streamer of every class will take some time and should be made a seperate issue.  Making things backwards compatible is not part of this issue. 

With the knowledge that the event model would be constantly changing, we (in a software meeting at some point) made the decision that the data should be analyzed with the corresponding release.  That's why the release notes of every release indicates what pass of the data it corresponds to.  Users should not be using the master to analyze data.  Up to this point, this has worked well.  That said, I'm making these changes in preparation for pass 1 of the 2016 data so there is time pressure.

I assigned the merge only.  The idea is that you test my changes before we merge in.  This is something that I want to start doing instead of just merging changes myself.

**Comment by mholtrop** [comment]
OK, noted, though we only need to change one streamer. 
I’ll try to complete the test soon and merge. I agree with cross assigning merges.

**Pull request merged**
